### ISSUE TITLE
Can't run bin/server

### ISSUE THREAD

**Issue by davisagli** [plone/plone.server#1]
I cloned, ran buildout, tried to run bin/server, and got:

```
Traceback (most recent call last):
  File "bin/server", line 71, in <module>
    import plone.server.server
  File "/Users/davisagli/Plone/plone.server/src/plone.server/plone/server/server.py", line 3, in <module>
    from plone.server.factory import make_app
  File "/Users/davisagli/Plone/plone.server/src/plone.server/plone/server/factory.py", line 15, in <module>
    from plone.server.traversal import TraversalRouter
  File "/Users/davisagli/Plone/plone.server/src/plone.server/plone/server/traversal.py", line 8, in <module>
    from parts.packages.zope.security.checker import selectChecker, \
ImportError: No module named 'parts'
```

Some step missing from setup instructions?

**Comment by davisagli** [comment]
Just a bad import, fixed in https://github.com/plone/plone.server/pull/2/commits/d7d88a41b7f485f1e3d29a885edab7c3c0157ac2
