### ISSUE TITLE
Unauthorized access results in 500

### ISSUE THREAD

**Issue by jaroel** [plone/plone.server#30]
https://github.com/plone/plone.server/blob/master/src/plone.server/plone/server/traversal.py#L214
refers to txn, which isn't started for non-writable requests.
Which results in:
```

MainThread plone.server.traversal: Not authorized to render operation 4c8af77fe03645d2a14dd2dba64cf8ce
Traceback (most recent call last):
  File "/Users/roelbruggink/Develop/plone/plone.server/src/plone.server/plone/server/traversal.py", line 207, in handler
    view_result = await self.view()
  File "/Users/roelbruggink/Develop/plone/plone.server/src/plone.server/plone/server/security.py", line 80, in check
    raise Unauthorized(obj, name, permission)
zope.security.interfaces.Unauthorized: (<plone.server.api.portal.DefaultGET object at 0x10209a9b0>, '__call__', 'plone.GetPortals')
MainThread        aiohttp.web: Error handling request
Traceback (most recent call last):
  File "/Users/roelbruggink/Develop/plone/plone.server/src/plone.server/plone/server/traversal.py", line 207, in handler
    view_result = await self.view()
  File "/Users/roelbruggink/Develop/plone/plone.server/src/plone.server/plone/server/security.py", line 80, in check
    raise Unauthorized(obj, name, permission)
zope.security.interfaces.Unauthorized: (<plone.server.api.portal.DefaultGET object at 0x10209a9b0>, '__call__', 'plone.GetPortals')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/roelbruggink/.buildout/eggs/aiohttp-1.0.5-py3.5-macosx-10.11-x86_64.egg/aiohttp/server.py", line 261, in start
    yield from self.handle_request(message, payload)
  File "/Users/roelbruggink/.buildout/eggs/aiohttp-1.0.5-py3.5-macosx-10.11-x86_64.egg/aiohttp/web.py", line 88, in handle_request
    resp = yield from handler(request)
  File "/Users/roelbruggink/Develop/plone/plone.server/src/plone.server/plone/server/traversal.py", line 214, in handler
    await sync(request)(txn.abort)
UnboundLocalError: local variable 'txn' referenced before assignment

```

Locally I can fix this by removing `await sync(request)(txn.abort)`, but I don't know if this is  by design?

Shouldn't every request be in a transaction, just in case someone is writing in a GET?

**Comment by vangheem** [comment]
Yes, by design writes are not allowed in a GET.
